### ISSUE TITLE
Protocol not followed

### ISSUE THREAD

**Issue by Dolck** [Jullekungfu/SpaceDefence#3]
Define what should happen when protocol is not followed in the parsing

**Comment by antonlin1** [comment]
Console print:

Exception in thread "Thread-2" java.lang.NullPointerException
at client.ParseBytes.bytesToInt(ParseBytes.java:154)
at client.ParseBytes.run(ParseBytes.java:116)
NegativeArraySizeException when declaring msg.

**Comment by Dolck** [comment]
Protocol works like a charm right now :)
